Coding Standards from Ticket 47632
ClassicPress/ClassicPress pull request #1102
Opened 2022-09-02 16:49 UTC by mattyrob

## Description
## Description
This PR includes all relevant changes included in upstream ticket 47632:
https://core.trac.wordpress.org/ticket/47632
Not all of the 27 commits were necessary or needed.

## Motivation and context
Improve coding standards for readability and to aid move to PHP 8 and 8.1 compatibility.
It also commences work as described in the discussion on #1098 

## How has this been tested?
Coding standards and PHPUnit tests run and pas locally after these changes.

## Screenshots
N/A

## Types of changes
- Bug fix / Enhancement

2022-09-29 11:50 UTC, xxsimoxx requested changes
Another warning: `function 'is_privacy_policy' not found or invalid function name in src/wp-includes/template-loader.php on line 71`

2022-09-29 11:50 UTC, xxsimoxx commented on src/wp-includes/template-loader.php
> +			}
`is_privacy_policy` and `get_privacy_policy_template` are since WP-5.2.
The others are OK.

2022-10-10 14:08 UTC, xxsimoxx approved these changes
Tested (together with #1117) on a live site with `WP_DEBUG` turned on, done common tasks and left in place for 3 days without any error or warning.

2022-10-13 15:12 UTC, mattyrob commented
Discussed at weekly PR review and agreed for merge.

2022-10-13 15:13 UTC, merged