Only style the range input control on the Revision screen
ClassicPress/ClassicPress pull request #1573
Opened 2024-10-02 16:22 UTC by wolffe

This fixes the broken range input control on non-Revision screens, such as theme or plugin settings pages.

Whenever am `<input type="range">` element is added to a theme or plugin settings page, it looks broken because it inherits the styles from the Revisions screen. The range input control styles should be isolated to the Revisions screen only, and appear as a native element on all the other screens.

**Revisions screen**

![image](https://github.com/user-attachments/assets/04273e47-01c4-4af9-bc3d-97dfde3b9a83)

**A theme settings screen (before)**

![image](https://github.com/user-attachments/assets/7458391f-f2fd-4c69-86d0-aea677bb7a21)

**A theme settings screen (after)**

![image](https://github.com/user-attachments/assets/7803269e-76b3-4aed-b5e9-c6fa8b26b013)

2024-10-03 13:52 UTC, KTS915 requested changes
The file `revisions.css` is also used in the Customizer, and these changes will have effects there. So, for every entry where you have added a new `.sliders-control ` prefix, you need also to create an identical entry with the prefix `.wp-picker-holder `.

2024-10-03 14:09 UTC, wolffe commented
@KTS915 Do you have a screenshot of a slider in the Customizer? I don't have any themes with sliders in the options to cehck myself.

2024-10-03 18:08 UTC, KTS915 approved these changes
Glad to see you resisted the temptation to merge apparently similar code blocks, as they have to stay separate to work!

2024-10-04 08:50 UTC, wolffe commented
I know. There's nothing we can do until reaching version 3.

2024-10-04 10:56 UTC, KTS915 commented
No, it's not about semver in ClassicPress. It's about the different browsers. These CSS rules only work if they are kept separate because that's the way the browsers are. We can't do anything about that until the browsers reach greater consensus on how to handle ranges.

2024-10-04 11:07 UTC, wolffe commented
Interesting, I didn't know about this. And I have coded a few range sliders in my life :)

But I only support modern browsers, such as Chrome and Firefox. So, no Safari or Edge or anything else, so maybe that's a reason I never noticed.

2024-10-04 11:13 UTC, wolffe commented
Good to know, thanks!

2024-10-17 15:18 UTC, merged