Add admin notice functions
ClassicPress/ClassicPress pull request #1650
Opened 2024-11-16 10:05 UTC by mattyrob

## Description
As suggested on Zulip, this PR backports several upstream changes to introduce some admin notice functions and associated tests.

The backports are:
https://core.trac.wordpress.org/changeset/56408
https://core.trac.wordpress.org/changeset/56603
https://core.trac.wordpress.org/changeset/56654
https://core.trac.wordpress.org/changeset/57279

These introduce:
`wp_get_admin_notice()`
`wp_admin_notice()`

## Motivation and context
Provides functions for use in Themes and Plugins and also offers a consistent way to programmatically show admin notices and errors.

## How has this been tested?
Local testing during process of backporting, new tests included in the PR.

Testing on `wp-login.php` that also seems to use this function shows same visual output.

## Screenshots
### Before
![Screenshot 2024-11-16 at 10 00 36](https://github.com/user-attachments/assets/0e63806a-60d1-4d03-abce-9bf15bdb72ba)
![Screenshot 2024-11-16 at 10 00 54](https://github.com/user-attachments/assets/3e49adba-12ed-41e3-a6ce-9fb402c4763d)

### After
![Screenshot 2024-11-16 at 10 01 31](https://github.com/user-attachments/assets/cdc53745-4a60-4ede-be1b-ba24de3ac205)
![Screenshot 2024-11-16 at 10 01 15](https://github.com/user-attachments/assets/168e6501-5417-4a29-be5e-784c4e322f46)

## Types of changes
- New feature

2024-11-16 14:51 UTC, KTS915 requested changes
I think some more changesets need to be backported, specifically:

[[56409]](https://core.trac.wordpress.org/changeset/56409), 
[[56410]](https://core.trac.wordpress.org/changeset/56410), 
[[56518]](https://core.trac.wordpress.org/changeset/56518), 
[[56570]](https://core.trac.wordpress.org/changeset/56570),
[[56571]](https://core.trac.wordpress.org/changeset/56571), 
[[56572]](https://core.trac.wordpress.org/changeset/56572), 
[[56573]](https://core.trac.wordpress.org/changeset/56573), 
[[56576]](https://core.trac.wordpress.org/changeset/56576), 
[[56589]](https://core.trac.wordpress.org/changeset/56589), 
[[56590]](https://core.trac.wordpress.org/changeset/56590), 
[[56597]](https://core.trac.wordpress.org/changeset/56597).

https://core.trac.wordpress.org/changeset/56599
https://core.trac.wordpress.org/changeset/57087

2024-11-18 13:13 UTC, xxsimoxx commented
The new function can be used also in `src/wp-includes/classicpress/class-wp-compat.php`.
I've a commit ready that I can push if you want.

2024-11-18 15:25 UTC, mattyrob commented
> The new function can be used also in `src/wp-includes/classicpress/class-wp-compat.php`. I've a commit ready that I can push if you want.

@xxsimoxx - please go ahead and add your commit for `src/wp-includes/classicpress/class-wp-compat.php`.

2025-01-02 17:39 UTC, KTS915 approved these changes

2025-01-09 16:34 UTC, merged