Merge/wp r48133 - Backport of upstream ticket 8973
ClassicPress/ClassicPress pull request #602
Opened 2020-08-06 08:24 UTC by mattyrob

## Description
Function get_page_of_comment() returns incorrect page numbers
https://core.trac.wordpress.org/ticket/8973

## Motivation and context
This is an old bug that has now been fixed upstream, this is a back port of the 2 fixing commits. Further details in the two commit notes.

## How has this been tested?
Unit tests included in patch

## Types of changes
- Bug fix

2021-05-07 15:43 UTC, mattyrob commented
This patch includes back ported unit tests and the files changes are checked and identical to those changes made in the patch.

2021-05-13 23:49 UTC, nylen requested changes

2021-05-13 23:49 UTC, nylen commented on src/wp-includes/comment-template.php
>   *
This was removed in https://core.trac.wordpress.org/changeset/48140:

```suggestion
 * @since WP-1.5.0
 *
```

2021-05-13 23:49 UTC, nylen commented on src/wp-includes/comment.php
> +		 * @since 5.5.0
```suggestion
		 * @since WP-5.5.0
```

2021-05-13 23:49 UTC, nylen commented on tests/phpunit/tests/comment/getPageOfComment.php
> +	 * @ticket 8973
```suggestion
	 * @see https://core.trac.wordpress.org/ticket/8973
```

2021-05-13 23:49 UTC, nylen commented on tests/phpunit/tests/comment/getPageOfComment.php
> +	 * @ticket 8973
```suggestion
	 * @see https://core.trac.wordpress.org/ticket/8973
```

2021-05-13 23:49 UTC, nylen commented on src/wp-includes/comment.php
> +function wp_get_unapproved_comment_author_email() {
This also needs to be done using a full backport of the changeset(s) that added this function.

2021-05-14 00:42 UTC, nylen commented on src/wp-includes/comment.php
> +function wp_get_unapproved_comment_author_email() {
Actually that's not quite right either. `wp_get_unapproved_comment_author_email` was added as part of a larger change: https://core.trac.wordpress.org/changeset/44659 / https://core.trac.wordpress.org/ticket/43857

If that is adopted then we would also need to backport https://core.trac.wordpress.org/ticket/49956 which is a bugfix for that change.

What should be done here is to make the change desired in the PR, but without using the `wp_get_unapproved_comment_author_email` function. The logic should look like what was present before that function was added: https://core.trac.wordpress.org/changeset/44659#file1

2021-05-14 01:04 UTC, nylen commented on src/wp-includes/comment-template.php
> +		}
```suggestion
	if ( is_user_logged_in() ) {
		$comment_args['include_unapproved'] = array( get_current_user_id() );
	} elseif ( ! empty( $comment_author_email ) ) {
		$comment_args['include_unapproved'] = array( $comment_author_email );
```

2021-05-14 01:09 UTC, nylen commented on src/wp-includes/comment.php
> +		}
```suggestion
		if ( is_user_logged_in() ) {
			$comment_args['include_unapproved'] = array( get_current_user_id() );
		} else {
			$commenter       = wp_get_current_commenter();
			$commenter_email = $commenter['comment_author_email'];
			if ( ! empty( $commenter_email ) ) {
				$comment_args['include_unapproved'] = array( $commenter_email );
			}
		}
```

2021-05-14 01:21 UTC, nylen commented
The entire `wp_get_unapproved_comment_author_email` function should be removed from this PR. This function with its use of the `$_GET['unapproved']` and `$_GET['moderation-hash']` parameters was added as part of https://core.trac.wordpress.org/changeset/44659, a separate change. https://core.trac.wordpress.org/changeset/48133 from this PR depends on that change, so what this PR should do is apply 48133 but modifying its logic as though 44659 never existed. This is the intent of my latest (untested) code suggestions.

Then, this PR needs further testing per the instructions at https://core.trac.wordpress.org/ticket/8973#comment:5 and https://core.trac.wordpress.org/ticket/8973#comment:16. As usual, performing and writing about this testing is part of what is necessary to fully understand the code changes and show that this PR is ready to be merged.

A bit complicated, and a low-impact fix, so I am removing this from the 1.3.0-rc1 milestone.

2021-11-11 16:55 UTC, merged