Merge/wp r46780
ClassicPress/ClassicPress pull request #789
Opened 2021-09-08 17:40 UTC by KTS915

Options, Meta APIs: Avoid a race condition causing the first of two subsequent requests updating different options at the same time to lose changes.

Every time an autoloaded option is updated or deleted, the alloptions cache is similarly updated. Due to the race condition, on any autoloaded option being updated, every other autoloaded option had its value set to the value at load time, causing a mismatch between the data in the persistent cache and the database.

This change introduces a $force_cache parameter for wp_load_alloptions() to force an update of the local alloptions cache from the persistent cache when an option is added, updated, or deleted, to minimize the chance of affecting other options.

Props fabifott, rmccue, tollmanz, johnjamesjacoby, spacedmonkey, dd32, jipmoors, tellyworth, jeremyclarke, joehoyle, boonebgorges, danielbachhuber, flixos90, jeichorn, mihdan, Grzegorz.Janoszka, SergeyBiryukov.
Merges [46753] and [46779] to the 5.3 branch.
Fixes #31245.

I have tested this in a local install with many custom options and have had no problems.

2021-09-08 18:09 UTC, nylen requested changes
The change itself is fine but the git history came out wrong on this PR, it includes a bunch of changes it shouldn't and the commit message from the original WP change(s) has been lost (this should be preserved by the backport script documented [here](https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#backporting-changes-from-wordpress)).

If you want, just leave this PR as-is and I will clean it up.

Is it just https://core.trac.wordpress.org/changeset/46780 that needs to be backported or are there other changesets?

2021-09-08 18:14 UTC, KTS915 commented
Thanks! Hmm, it was all going so well until Github Desktop failed to be able to login to my Github account. It appears that the problem I'm having is a known issue. And there was I thinking that I might at last have been able to do a changeset.

2021-09-08 22:06 UTC, nylen commented
You also need to reset your local repo to the latest official code before starting a branch. That process is described (somewhat) here: https://www.classicpress.net/github-tutorial-step-8-fetch-and-merge/

2021-09-09 00:29 UTC, nylen approved these changes
Heh... `alloptions` is awful.

This change has no effect unless a site is using a [persistent object cache](https://developer.wordpress.org/reference/classes/WP_Object_Cache/#role-of-the-wordpress-object-cache). In that case, this change will slightly decrease performance but will significantly decrease the likelihood of a race condition where options are not updated as they should be.

2021-09-09 00:30 UTC, merged

2021-09-10 15:32 UTC, KTS915 commented
> Heh... `alloptions` is awful.

> This change has no effect unless a site is using a persistent object cache. In that case, this change will slightly decrease performance but will significantly decrease the likelihood of a race condition where options are not updated as they should be.

Indeed. But for people like me who run membership sites and intranets with a persistent object cache, it's pretty important.