Changeset 47582: Posts, Post Types: Pass the post object to the before_delete_post, delete_post, deleted_post, and after_delete_post actions.
ClassicPress/ClassicPress pull request #805
Opened 2021-10-01 15:13 UTC by KTS915

## Description
Backports changeset 47582: Posts, Post Types: Pass the post object to the before_delete_post, delete_post, deleted_post, and after_delete_post actions.

## Motivation and context
From [Trac](https://core.trac.wordpress.org/ticket/30940):  When using `wp_delete_post()`, four actions are fired: `before_delete_post`, `delete_post`, `deleted_post` and `after_delete_post`. All of them get the `$postid` argument.

In some situations, it might be useful to have some extra information about the post being deleted, to perform different actions depending on things like the post date or the post type. With extensive usage of custom post types, this becomes more evident.

We can always get that data from the post ID being passed as an argument on those four actions, but that will add extra database calls that we can easily avoid. Early in `wp_delete_post()`, we do get the post row object from the database to check for things like post type and post parent. It seems a waste to recreate that data again if needed, plus it is not there anymore on the last two actions due to, well, post deletion. This limits what can be done on those last two actions in a granular way (no different deleted_post action callback workflow on a per post type basis, for example).

## How has this been tested?
Tested on local install and upstream.

## Types of changes
Exposes the `$post` object when deleting a post, which avoids having to make an extra call to the database using `get_post( $postid )`

2021-12-14 17:36 UTC, bahiirwa approved these changes

2021-12-14 17:37 UTC, bahiirwa commented on src/wp-includes/post.php
> +	 * @since 3.2.0
@since needs WP-3.2.0 and WP-5.5.0

2021-12-14 17:39 UTC, bahiirwa requested changes
Only the @ since need some updates to follow the usual docs structure. Otherwise, code looks good as upstream.

2022-09-30 08:42 UTC, mattyrob approved these changes

2022-10-06 15:59 UTC, merged